# Generated by Django 4.2.16 on 2024-11-19 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_rename_fluent_languges_customuser_fluent_languages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='prifix',
        ),
        migrations.AddField(
            model_name='doctor',
            name='prefix',
            field=models.CharField(default='Dr', max_length=10),
        ),
    ]
