# Generated by Django 4.2.16 on 2024-11-19 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_answered',
            field=models.BooleanField(default=False),
        ),
    ]
