# Generated by Django 4.2.21 on 2025-06-07 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chatbot_api", "0002_message_is_answered"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="unanswered_question",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="messages",
                to="chatbot_api.unansweredquestion",
            ),
        ),
        migrations.AddField(
            model_name="unansweredquestion",
            name="original_message",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="unanswered_questions",
                to="chatbot_api.message",
            ),
        ),
        migrations.AlterField(
            model_name="chatsession",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_sessions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
