export type TFormData = {
  fullNameEnglish: string;
  fullNameArabic: string;
  prefix: string;
  email: string;
  phone: string;
  username: string;
  password: string;
  confirmPassword: string;
  dateOfBirth: string;
  gender: string;
  nationality: string;
  countryOfResidence: string;
  fluentLanguages: string[];
  highestDegree: string;
  institutionName: string;
  graduationYear: number | null;
  category: string;
  specialization: string;
  yearsOfExperience: number | null;
  licenseNumber: string;
  licensingOrganization: string;
  workingInClinic: string;
  clinicName: string;
  availabilityForSessions: string;
  cv: File | null;
  certifications: File | null;
  anotherQualification1?: File | null;
  anotherQualification2?: File | null;
};

export type TFormErrors = {
  fullNameEnglish?: string;
  fullNameArabic?: string;
  prefix?: string;
  email?: string;
  phone?: string;
  username?: string;
  password?: string;
  confirmPassword?: string;
  dateOfBirth?: string;
  gender?: string;
  nationality?: string;
  countryOfResidence?: string;
  fluentLanguages?: string;
  highestDegree?: string;
  institutionName?: string;
  graduationYear?: string;
  category?: string;
  specialization?: string;
  yearsOfExperience?: string;
  licenseNumber?: string;
  licensingOrganization?: string;
  workingInClinic?: string;
  clinicName?: string;
  availabilityForSessions?: string;
  cv?: string;
  certifications?: string;
  multipleQualifications?: string;
  additionalQualifications?: string;
};
