# Generated by Django 5.1.1 on 2024-10-06 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_remove_patient_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='fluent_languges',
            new_name='fluent_languages',
        ),
    ]
