# Generated by Django 4.2.16 on 2024-11-19 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_remove_doctor_prifix_doctor_prefix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='prefix',
        ),
        migrations.AddField(
            model_name='doctor',
            name='prifix',
            field=models.CharField(default='Dr', max_length=100),
        ),
    ]
